export const desc =  [{"blacklist":"Use this function to Blacklist an account, can be called by blacklister only"},
{"burn":"Use this function to Burn Stable coin from the minted allowance, Can only be called by minters"},
{"configureMinter":"Use this function to Add or update Minters with given stable coin amount"},
{"mint":"Use this function to Mint new Stable Coins, Can only be called from minters"},
{"pause":"Use this function to be called by the owner to pause Smart Contract"},
{"removeMinter":"Use this function to Remove Minter, Can only be called from master minter"},
{"transfer":"Use this function To Transfer Stable coin to an address"},
{"approve":"Use this function toProvide approval to given address and amount to transfer from source account"},
{"transferFrom":"Use this function to Transfer the approved amount from the approval account"},
{"transferOwnership":"Use this function to allows the current owner to transfer control of the contract to a new owner"},
{"unBlacklist":"Use this function to Remove account from blacklist, can be called by blacklister only"},
{"Unpause":"Use this function to unpause Smart Contract can be called by the owner"},
{"updateBlacklister":"Use this function to Assign new Blacklister, can only be called by current blacklister"},
{"updateMasterMinter":"Use this function To Update master minter, can only be called from current masterminter"},
{"updatePauser":"Use this function to Update New Pauser, can only be called from current pauser"},
{"Allowance":"Use this function to find out Get allowed amount for an account"},
{"balanceOf":"Use this function to find out the Balance of Stable Coin tokens at any particular Address"},
{"Blacklister":"Use this function to find out the Blacklister Address"},
{"Decimals":"Use this function to find out Number of Decimals for Stable Coin"},
{"isBlacklisted":"Use this function to Checks if account is blacklisted"},
{"isMinter":"Use this function to find out whether address is minter or not"},
{"minterAllowance":"Use this function to find out the remaining Minter Allowance left for a particular minter"},
{"Name":"Use this function to Get the name of Stable Coin"},
{"owner":"Use this function to Get Current Owner of the Stable coin Smart contract"},
{"paused":"Use this function to find out if the Stable Coin contract is paused or not"},
{"Pauser":"Use this function to find out Current Pauser Address"},
{"stableCoinImpl":"Use this function to Get Stable Coin Contract Address"},
{"symbol":"Use this function to Get Stable Coin Symbol"},
{"totalBurned":"Use this function to Get Total Burned tokens"},
{"totalMinted":"Use this function to Get total minted tokens"},
{"totalSupply":"Use this function to Get Total Supply of the Stable Coin"}]
