export const LOADING = "LOADING";
export const INVALID_TOKEN = "INVALID_TOKEN";
export const INITIALIZE = "INITIALIZE";
export const REQUEST_LOAN = "REQUEST-LOAN";
export const LOAN_TRANSFER = "LOAN_TRANSFER";
export const REJECT_LOAN = "REJECT_LOAN";
export const SETTLE_LOAN = "SETTLE_LOAN";

export const LOANDATA = "LOANDATA";
export const PENDINGLOANDATA = "PENDINGLOANDATA";
export const APPROVEDLOANDATA = "APPROVEDLOANDATA";
export const REJECTEDLOANDATA = "REJECTEDLOANDATA";
export const SETTLEDLOANDATA = "SETTLEDLOANDATA";
export const SINGLESTATE = "SINGLESTATE";

export const GETINFO = 'GETINFO';
export const GETPEERS = 'GETPEERS';

export const GET_ME = "GET_ME";

export const GET_PENDING_COUNT = "GET_PENDING_COUNT"; 
export const GET_REJECTED_COUNT = "GET_REJECTED_COUNT";
export const GET_APPROVED_COUNT = "GET_APPROVED_COUNT";
export const GET_SETTLED_COUNT = "GET_SETTLED_COUNT";
 